# Site settings
title: STOOPID HYPE
email: your_email@example.com
author: Arkady Pevzner
description: "STOOPID HYPE"
baseurl: ""
url: "http://rkdeez.github.io"
google_analytics:
animated: false
show_related_posts: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true
